#!/usr/bin/env bash
# this configures a Nginx server to listen to port 80
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
systemctl stop nginx
